name: Question/Support
description: Ask a question about using pg-cel
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please provide as much detail as possible to help us give you the best answer.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you've checked these resources first
      options:
        - label: I have read the [README.md](../blob/main/README.md)
        - label: I have checked the [EXAMPLES.md](../blob/main/EXAMPLES.md) for similar use cases
        - label: I have searched existing issues and discussions
        - label: I have consulted the [TROUBLESHOOTING.md](../blob/main/TROUBLESHOOTING.md) guide

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - Installation/Setup
        - CEL Expression Syntax
        - Performance/Optimization
        - Integration with PostgreSQL
        - Build/Development
        - Configuration
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: question-details
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Please describe your question in detail
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to achieve
      placeholder: |
        What are you trying to accomplish?
        What's your specific use case?
        What approach have you tried so far?

  - type: dropdown
    id: postgresql-version
    attributes:
      label: PostgreSQL Version
      description: Which PostgreSQL version are you using? (if applicable)
      options:
        - Not applicable
        - PostgreSQL 14
        - PostgreSQL 15  
        - PostgreSQL 16
        - PostgreSQL 17
        - Other

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you using? (if applicable)
      options:
        - Not applicable
        - Linux (Ubuntu/Debian)
        - Linux (RHEL/CentOS/Fedora)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (WSL)
        - Other

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: If relevant, provide a code example or SQL query
      placeholder: |
        -- Your SQL query or code example here
        SELECT cel_eval('your expression', 'your data');
      render: sql

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What result or behavior are you expecting?
      placeholder: What should happen when you run your code?

  - type: textarea
    id: current-outcome
    attributes:
      label: Current Outcome
      description: What's actually happening? (if different from expected)
      placeholder: What's currently happening instead?

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might be helpful
      placeholder: |
        - Error messages (if any)
        - Configuration details
        - Performance requirements
        - Any other relevant context
