name: BDD Tests

on:
  push:
    branches: [ feature/godog-testing ]
  pull_request:
    branches: [ main ]
    paths:
      - 'features/**'
      - 'godog_*.go'
      - 'setup_bdd_tests.sh'

jobs:
  bdd-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        postgres-version: [14, 15, 16, 17]
        go-version: ['1.23']

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_pgcel
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Install PostgreSQL client and dev packages
      run: |
        # Add PostgreSQL official APT repository
        curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update
        # Install build dependencies
        sudo apt-get install -y build-essential gcc make pkg-config
        sudo apt-get install -y postgresql-client postgresql-server-dev-${{ matrix.postgres-version }}

    - name: Set PG_CONFIG environment
      run: |
        echo "PG_CONFIG=/usr/lib/postgresql/${{ matrix.postgres-version }}/bin/pg_config" >> $GITHUB_ENV
        # Verify pg_config is available
        ls -la /usr/lib/postgresql/${{ matrix.postgres-version }}/bin/pg_config
        /usr/lib/postgresql/${{ matrix.postgres-version }}/bin/pg_config --version

    - name: Install Go dependencies
      run: |
        echo "Installing Go dependencies..."
        go mod download
        go mod verify
        echo "Go dependencies installed successfully"

    - name: Build pg-cel extension
      env:
        CGO_ENABLED: 1
        CC: gcc
        V: 1
      run: |
        export PG_CONFIG=/usr/lib/postgresql/${{ matrix.postgres-version }}/bin/pg_config
        echo "Building with PostgreSQL version: ${{ matrix.postgres-version }}"
        echo "PG_CONFIG path: $PG_CONFIG"
        echo "Go version: $(go version)"
        echo "CGO_ENABLED: $CGO_ENABLED"
        echo "CC: $CC"
        echo "Platform: $(uname -s)"
        echo "Architecture: $(uname -m)"
        # Test Go build capability
        echo "Testing Go build..."
        go build -buildmode=c-archive -o test.a main.go || echo "Go build test failed"
        ls -la test.a 2>/dev/null && rm test.a || echo "Go archive test not found"
        # Run actual build
        ./build.sh

    - name: Install pg-cel extension
      run: |
        export PG_CONFIG=/usr/lib/postgresql/${{ matrix.postgres-version }}/bin/pg_config
        sudo make install

    - name: Setup test database
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: postgres
        TEST_DB: test_pgcel
      run: |
        # Wait for PostgreSQL to be ready
        echo "Waiting for PostgreSQL ${{ matrix.postgres-version }} to be ready..."
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Attempt $i: PostgreSQL not ready yet, waiting..."
          sleep 2
        done
        
        # Verify PostgreSQL is actually ready
        if ! pg_isready -h localhost -p 5432 -U postgres; then
          echo "PostgreSQL failed to become ready after 60 seconds"
          exit 1
        fi
        
        echo "PostgreSQL is ready. Creating test database..."
        # The database should already exist from the service, but let's make sure
        createdb test_pgcel 2>/dev/null || echo "Database test_pgcel already exists"
        
        echo "Installing pg-cel extension..."
        # Enable pg-cel extension
        psql -d test_pgcel -c "CREATE EXTENSION IF NOT EXISTS pg_cel;"
        
        echo "Verifying pg-cel extension works..."
        # Verify extension works
        psql -d test_pgcel -c "SELECT cel_eval('1 + 1') as test;" || {
          echo "Extension test failed, checking extension status..."
          psql -d test_pgcel -c "SELECT * FROM pg_extension WHERE extname='pg_cel';"
          exit 1
        }

    - name: Run BDD tests
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: postgres
        TEST_DB: test_pgcel
        POSTGRES_USER: postgres
      run: |
        echo "Running BDD tests with environment:"
        echo "PGHOST=$PGHOST"
        echo "PGPORT=$PGPORT"
        echo "PGUSER=$PGUSER"
        echo "TEST_DB=$TEST_DB"
        echo "POSTGRES_USER=$POSTGRES_USER"
        
        # Verify database connectivity before running tests
        echo "Testing database connectivity..."
        psql -d test_pgcel -c "SELECT version();" || {
          echo "Database connectivity test failed"
          exit 1
        }
        
        # Run the actual BDD tests
        go test -v -godog.format=pretty ./godog_main_test.go ./godog_test.go

    - name: Run BDD tests with JUnit output
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: postgres
        TEST_DB: test_pgcel
        POSTGRES_USER: postgres
      run: |
        go test -v -godog.format=junit:bdd-results.xml ./godog_main_test.go ./godog_test.go

    - name: Upload BDD test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bdd-test-results-pg${{ matrix.postgres-version }}
        path: bdd-results.xml

    - name: Run BDD tests with coverage
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: postgres
        TEST_DB: test_pgcel
        POSTGRES_USER: postgres
      run: |
        go test -v -coverprofile=bdd-coverage.out ./godog_main_test.go ./godog_test.go

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: bdd-coverage-pg${{ matrix.postgres-version }}
        path: bdd-coverage.out
