name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GO_VERSION: '1.22'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: ['14', '15', '16', '17']
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Install PostgreSQL ${{ matrix.pg_version }}
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc
        sudo apt-get update
        sudo apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }} build-essential
        
    - name: Set PostgreSQL environment
      run: |
        echo "PATH=/usr/lib/postgresql/${{ matrix.pg_version }}/bin:$PATH" >> $GITHUB_ENV
        echo "PG_CONFIG=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config" >> $GITHUB_ENV
        
    - name: Check PostgreSQL installation
      run: |
        which pg_config || echo "pg_config not found"
        pg_config --version || echo "pg_config failed"
        ls -la $(pg_config --bindir) || echo "PostgreSQL bindir listing failed"
        
    - name: Download Go dependencies
      run: go mod download
      
    - name: Get extension version
      id: get_version
      run: |
        VERSION=$(grep "default_version" pg_cel.control | sed "s/default_version = '\(.*\)'/\1/" | tr -d "'" | tr -d ' ')
        if [ -z "$VERSION" ]; then
          VERSION="1.0"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extension version: $VERSION"
      
    - name: Build extension
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Verify build output
      run: |
        echo "Checking build artifacts..."
        ls -la *.so || echo "No .so files found"
        ls -la pg_cel* || echo "No pg_cel files found"
        
    - name: Install extension
      run: |
        # Ensure we're using the correct pg_config
        echo "Using pg_config: $(which pg_config)"
        echo "PostgreSQL version: $(pg_config --version)"
        echo "Library directory: $(pg_config --pkglibdir)"
        echo "Extension directory: $(pg_config --sharedir)/extension"
        
        # Verify the directories exist
        sudo mkdir -p "$(pg_config --pkglibdir)"
        sudo mkdir -p "$(pg_config --sharedir)/extension"
        
        # Install with explicit PG_CONFIG
        sudo PG_CONFIG="/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config" PATH="/usr/lib/postgresql/${{ matrix.pg_version }}/bin:$PATH" make install
        
        # Verify installation
        echo "Verifying installation..."
        ls -la "$(pg_config --pkglibdir)/pg_cel.so" || echo "WARNING: pg_cel.so not found in expected location"
        ls -la "$(pg_config --sharedir)/extension/pg_cel.control" || echo "WARNING: pg_cel.control not found in expected location"
        ls -la "$(pg_config --sharedir)/extension/pg_cel--*.sql" || echo "WARNING: SQL files not found in expected location"
        
    - name: Test build
      run: |
        # Initialize and run PostgreSQL with the correct version
        export PATH="/usr/lib/postgresql/${{ matrix.pg_version }}/bin:$PATH"
        
        # Initialize a fresh PostgreSQL data directory for this version
        sudo mkdir -p /tmp/pg_data_${{ matrix.pg_version }}
        sudo chown postgres:postgres /tmp/pg_data_${{ matrix.pg_version }}
        
        # Initialize the database with the correct version
        sudo -u postgres /usr/lib/postgresql/${{ matrix.pg_version }}/bin/initdb -D /tmp/pg_data_${{ matrix.pg_version }}
        
        # Start PostgreSQL directly with the correct version
        sudo -u postgres /usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_ctl -D /tmp/pg_data_${{ matrix.pg_version }} -l /tmp/pg_log_${{ matrix.pg_version }} start
        
        # Wait for PostgreSQL to be ready
        sleep 5
        
        # Create test database and test the extension
        sudo -u postgres /usr/lib/postgresql/${{ matrix.pg_version }}/bin/createdb -p 5432 test_db
        sudo -u postgres /usr/lib/postgresql/${{ matrix.pg_version }}/bin/psql -p 5432 -d test_db -c "CREATE EXTENSION pg_cel;"
        sudo -u postgres /usr/lib/postgresql/${{ matrix.pg_version }}/bin/psql -p 5432 -d test_db -c "SELECT cel_eval('2 + 3');"
        
        # Stop the PostgreSQL instance
        sudo -u postgres /usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_ctl -D /tmp/pg_data_${{ matrix.pg_version }} stop
        
    - name: Package artifacts
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        mkdir -p dist/linux-pg${{ matrix.pg_version }}
        # On Linux, the extension creates a .so file
        cp pg_cel.so dist/linux-pg${{ matrix.pg_version }}/ || echo "Warning: pg_cel.so not found"
        
        # Always copy the standard SQL file
        cp pg_cel--*.sql dist/linux-pg${{ matrix.pg_version }}/ || echo "Warning: SQL files not found"
        
        cp pg_cel.control dist/linux-pg${{ matrix.pg_version }}/ || echo "Warning: pg_cel.control not found"
        cp README.md dist/linux-pg${{ matrix.pg_version }}/ || echo "Warning: README.md not found"
        cp LICENSE dist/linux-pg${{ matrix.pg_version }}/ || echo "Warning: LICENSE not found"
        tar -czf pg-cel-linux-pg${{ matrix.pg_version }}.tar.gz -C dist/linux-pg${{ matrix.pg_version }} . || echo "Warning: tar failed"
        
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pg-cel-linux-pg${{ matrix.pg_version }}
        path: pg-cel-linux-pg${{ matrix.pg_version }}.tar.gz

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        pg_version: ['14', '15', '16', '17']
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Install PostgreSQL ${{ matrix.pg_version }}
      run: |
        brew update
        brew install postgresql@${{ matrix.pg_version }}
        brew link postgresql@${{ matrix.pg_version }} --force
        
    - name: Set PostgreSQL environment
      run: |
        echo "PATH=/opt/homebrew/opt/postgresql@${{ matrix.pg_version }}/bin:$PATH" >> $GITHUB_ENV
        echo "PG_CONFIG=/opt/homebrew/opt/postgresql@${{ matrix.pg_version }}/bin/pg_config" >> $GITHUB_ENV
        echo "PGDATA=/opt/homebrew/var/postgresql@${{ matrix.pg_version }}" >> $GITHUB_ENV
        
    - name: Check PostgreSQL installation
      run: |
        which pg_config || echo "pg_config not found"
        pg_config --version || echo "pg_config failed"
        ls -la $(pg_config --bindir) || echo "PostgreSQL bindir listing failed"
        
    - name: Download Go dependencies
      run: go mod download
      
    - name: Get extension version
      id: get_version
      run: |
        VERSION=$(grep "default_version" pg_cel.control | sed "s/default_version = '\(.*\)'/\1/" | tr -d "'" | tr -d ' ')
        if [ -z "$VERSION" ]; then
          VERSION="1.0"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extension version: $VERSION"
      
    - name: Build extension
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Verify build output
      run: |
        echo "Checking build artifacts..."
        ls -la *.dylib || echo "No .dylib files found"
        ls -la *.so || echo "No .so files found"
        ls -la pg_cel* || echo "No pg_cel files found"
        
    - name: Install extension
      run: |
        # Ensure we're using the correct pg_config
        echo "Using pg_config: $(which pg_config)"
        echo "PostgreSQL version: $(pg_config --version)"
        echo "Library directory: $(pg_config --pkglibdir)"
        echo "Extension directory: $(pg_config --sharedir)/extension"
        make install
        
    - name: Test build
      run: |
        # Initialize and start PostgreSQL more reliably
        mkdir -p /tmp/pgdata
        initdb -D /tmp/pgdata
        pg_ctl -D /tmp/pgdata -l /tmp/logfile start
        sleep 5
        createdb test_db
        psql -d test_db -c "CREATE EXTENSION pg_cel;"
        psql -d test_db -c "SELECT cel_eval('2 + 3');"
        pg_ctl -D /tmp/pgdata stop
        
    - name: Package artifacts
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        mkdir -p dist/macos-pg${{ matrix.pg_version }}
        # On macOS, the extension can create either a .dylib or .so file
        if [ -f pg_cel.dylib ]; then
          cp pg_cel.dylib dist/macos-pg${{ matrix.pg_version }}/ || echo "Warning: pg_cel.dylib not found"
        elif [ -f pg_cel.so ]; then
          cp pg_cel.so dist/macos-pg${{ matrix.pg_version }}/ || echo "Warning: pg_cel.so not found"
        else
          echo "Warning: No extension binary found"
        fi
        
        # Always copy the standard SQL file
        cp pg_cel--*.sql dist/macos-pg${{ matrix.pg_version }}/ || echo "Warning: SQL files not found"
        
        cp pg_cel.control dist/macos-pg${{ matrix.pg_version }}/ || echo "Warning: pg_cel.control not found"
        cp README.md dist/macos-pg${{ matrix.pg_version }}/ || echo "Warning: README.md not found"
        cp LICENSE dist/macos-pg${{ matrix.pg_version }}/ || echo "Warning: LICENSE not found"
        tar -czf pg-cel-macos-pg${{ matrix.pg_version }}.tar.gz -C dist/macos-pg${{ matrix.pg_version }} . || echo "Warning: tar failed"
        
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pg-cel-macos-pg${{ matrix.pg_version }}
        path: pg-cel-macos-pg${{ matrix.pg_version }}.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: [build-linux]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Linux PG16 artifact
      uses: actions/download-artifact@v4
      with:
        name: pg-cel-linux-pg16
        path: .
      continue-on-error: true
        
    - name: Extract and test
      run: |
        if [ -f pg-cel-linux-pg16.tar.gz ]; then
          tar -xzf pg-cel-linux-pg16.tar.gz
          echo "Using downloaded artifacts"
        else
          echo "Artifact not found, will build locally for testing"
        fi
        ls -la
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        
    - name: Install PostgreSQL 16
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y postgresql-16 postgresql-server-dev-16
        
    - name: Build extension locally if needed
      run: |
        if [ ! -f pg_cel.so ]; then
          echo "Building extension locally for testing"
          go mod download
          chmod +x build.sh
          ./build.sh
          sudo make install
        fi
        
    - name: Run comprehensive tests
      run: |
        sudo systemctl start postgresql
        sudo -u postgres createdb test_db
        
        # Install the extension manually
        if [ -f pg_cel.so ]; then
          sudo cp pg_cel.so /usr/lib/postgresql/16/lib/ || echo "Warning: Could not copy pg_cel.so"
          sudo cp pg_cel.control /usr/share/postgresql/16/extension/ || echo "Warning: Could not copy pg_cel.control"
          sudo cp pg_cel--*.sql /usr/share/postgresql/16/extension/ || echo "Warning: Could not copy SQL files"
        fi
        
        # Create and test extension
        sudo -u postgres psql -d test_db -c "CREATE EXTENSION pg_cel;"
        
        # Run our test suite
        sudo -u postgres psql -d test_db -f test.sql

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Debug artifacts
      run: |
        echo "Listing all downloaded artifacts:"
        find artifacts -type f | sort
        
    - name: Create release directory
      run: |
        mkdir -p release
        find artifacts -name "*.tar.gz" -exec cp {} release/ \;
        echo "Contents of release directory:"
        ls -la release/
        
    - name: Ensure release assets exist
      run: |
        if [ -z "$(ls -A release/*.tar.gz 2>/dev/null)" ]; then
          echo "No release assets found, creating fallback asset"
          echo "This is a fallback release asset. Please check the build logs for errors." > release/README.txt
        fi
        
    - name: Generate release notes
      run: |
        echo "# pg-cel Release ${GITHUB_REF#refs/tags/}" > release_notes.md
        echo "" >> release_notes.md
        echo "PostgreSQL extension for CEL (Common Expression Language) evaluation." >> release_notes.md
        echo "" >> release_notes.md
        echo "## Supported Platforms" >> release_notes.md
        echo "- Linux (Ubuntu) with PostgreSQL 14, 15, 16, 17" >> release_notes.md
        echo "- macOS with PostgreSQL 14, 15, 16, 17" >> release_notes.md
        echo "" >> release_notes.md
        echo "## Installation" >> release_notes.md
        echo "1. Download the appropriate package for your platform and PostgreSQL version" >> release_notes.md
        echo "2. Extract the package: \`tar -xzf pg-cel-[platform]-pg[version].tar.gz\`" >> release_notes.md
        echo "3. Copy files to PostgreSQL directories (requires admin privileges)" >> release_notes.md
        echo "4. In PostgreSQL: \`CREATE EXTENSION pg_cel;\`" >> release_notes.md
        echo "" >> release_notes.md
        echo "## Features" >> release_notes.md
        echo "- Dynamic CEL expression evaluation with JSON data" >> release_notes.md
        echo "- High-performance dual caching system" >> release_notes.md
        echo "- Support for all CEL language features" >> release_notes.md
        echo "- Type-safe convenience functions" >> release_notes.md
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        body_path: release_notes.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
